---
name: Nginx Proxy Manager
version: "0.0.3"
slug: nginx
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/vguttmann/addon-nginx
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
image: "ghcr.io/vguttmann/{arch}-addon-nginx"
